<div class="page-header">
    <h1>Settings
        <small>You can modify site settings here</small>
    </h1>
</div>

<div class="tabbable">

    <ul class="nav nav-tabs">
        <li class="dropdown" id="content-tab">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Settings <b class="caret"></b></a>
            <ul id="content-tabs" class="dropdown-menu">

                
            </ul>
        </li>
        
    </ul>


    <div class="tab-content">
        <div class="tab-pane top-level-tab" id="tab-content">

            <div class="tabbable">
                
                <div class="tab-content">
                    <div class="tab-pane active" id="content">      
                        <div id="formWrapper" class="">
                            <?php echo $this->form; ?>
                        </div>
                    </div>  
                </div>
            </div>

        </div>

    </div>
</div>

<script type="text/javascript">
$(function() {
    newton.tabs.setupFromFieldsets();
});
</script>