
<div class="page-header">
    
    <div class="btn-group pull-right">
        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><i class="icon-pencil icon-white"></i> Create New Content</a>
        <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
        <ul class="dropdown-menu">
            <?php foreach(TypeManager::getInstance()->getTypes() as $type) : ?>
            <?php if($type->getIsPage()) { continue; } ?>
            <?php if(null !== $this->type && $type->getName() != $this->type->getName()) { continue; } ?>
            <?php $url = URL::route(array(
                'controller'    => 'item',
                'action'        => 'add',
                'type'          => $type->getName(),
                'is_page'       => $type->getIsPage(),
                'id'            => null
            )); ?>
            <li><a href="<?php echo $url?>"><?php echo $type->getLabel() ?></a></li>
            <?php endforeach; ?>
        </ul>
    </div>

<h1><?php echo $this->type->getPluralLabel(); ?> <small>Create and manage <?php echo $this->type->getPluralLabel(); ?></small></h1>

</div>

<div>
    <table cellpadding="0" cellspacing="0" border="0" class="datatable table table-striped table-bordered">
        <thead>
            <tr> 
                <?php foreach($this->type->getDatatableMappings() as $k => $v) : ?>
                    <th><?php echo $v?></th>
                <?php endforeach; ?>
                <th style="width: 70px;">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->items as $item) : ?>
            <?php
                $data       = $item->getData();
                $rewrite    = $item->getRewrite();
                $type       = $item->getType();
                $editUrl    = URL::route(array(
                    'controller'    => 'item',
                    'action'        => 'edit',
                    'type'          => $type->getName(),
                    'id'            => (string) $item->getId()
                ));
                $deleteUrl  = URL::route(array(
                    'controller'    => 'item',
                    'action'        => 'delete',
                    'type'          => $type->getName(),
                    'id'            => (string) $item->getId()
                )); 
            ?>
            <tr> 
                <?php foreach($this->type->getDatatableMappings() as $k => $v) : ?>
                    <td><?php echo isset($data[$k]) ? $data[$k] : '';?></td>
                <?php endforeach; ?>
                <td style="padding: 2px; text-align: center; width: 70px;">
                    <a href="<?php echo $editUrl;?>" class="btn btn-primary btn-small" rel="tooltip" title="Edit" id="edit">
                        <i class="icon-pencil icon-white"></i>
                    </a>
                    <a href="javascript:newton.modal.confirmDelete('<?php echo $deleteUrl; ?>');" class="btn btn-danger btn-small" rel="tooltip" title="Delete">
                        <i class="icon-trash icon-white"></i>
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>

    <script>
    $.extend( $.fn.dataTableExt.oStdClasses, {
        "sWrapper": "dataTables_wrapper form-inline"
    });
</script>

</div>